### PR TITLE
Disable ruleset tests

### PR DESCRIPTION
**Pull request by andylolz**
Profiling suggests this test is one of the slowest. It doesn’t appear to be used by the dashboard anyway. So disabling it should speed things up a bit, without causing issues for the dashboard.

Refs #129.

### CODE REVIEW

**Comment by andylolz** [comment]
Some crude benchmarking:

```shell
$ git checkout master
$ time python calculate_stats.py loop --folder millenniumchallenge

real    1m30.076s
user    1m26.325s
sys     0m2.056s
```

Re-running on this branch:

```shell
$ git checkout rm-ruleset-tests
$ time python calculate_stats.py loop --folder millenniumchallenge

real    1m5.361s
user    1m3.713s
sys     0m1.257s
```

So that’s about 17% faster.

**Comment by dalepotter** [comment]
Looking at the Dashboard code, it seems that there was an intention to use this on in [this page](https://github.com/IATI/IATI-Dashboard/blob/master/static/templates/rulesets.html), which for some reason was never decided to be made part of the live site. The non-public page can be previewed locally here (with old data):

image

Given the time needed to generate underlaying data as shown above, I'm approving this PR and have set up a new PR to remove the code from the Dashboard: https://github.com/IATI/IATI-Dashboard/pull/490

@bill-anderson - as you were around at the time of the Dashboard build, let me know if it not being included as a mistake somewhere, in which case this (and https://github.com/IATI/IATI-Dashboard/pull/490) can be reverted.

**Comment by andylolz** [comment]
It’s also worth removing these ruleset tests because they’re currently very broken. See: IATI/IATI-Rulesets#76.

**Comment by andylolz** [comment]
> @bill-anderson - as you were around at the time of the Dashboard build, let me know if rulesets not being included is a mistake somewhere

As mentioned on IATI/IATI-Dashboard#490: See IATI/IATI-Dashboard#108 for more information on this. Rulesets were removed from the dashboard way back in IATI/IATI-Dashboard@fa81205.

**Pull request merged**
