### PR TITLE
Humanitarian dashboard fixes

### PR DESCRIPTION
**Pull request by andylolz**
~~**Branched from #132, so that needs to be merged first.**~~ <-- UPDATE: That’s merged now.

This might look like it adds a bunch of stuff, but it actually only adds two lines of any consequence! These lines ensure that both `contains_humanitarian_scope` and `uses_humanitarian_clusters_vocab` can only be true if the activity is humanitarian.

This change means the scores for “appeal or emergency details” and “clusters” can’t go above 100%, while also ensuring the Grand Bargain agreed definition of humanitarian activities is preserved.

I’ve updated tests accordingly, and have added a couple more tests to ensure a non-humanitarian activity won’t be included in the “clusters” score or the “appeal or emergency details” score.

References https://github.com/IATI/IATI-Dashboard/issues/488#issuecomment-396893684.

This PR references IATI/IATI-Dashboard#485 and IATI/IATI-Dashboard#488. **It should fix both issues.**

### CODE REVIEW

**Comment by andylolz** [comment]
If this PR requires any further explanation, please message me on here or on skype.

It would be great to get this merged, because it fixes some major issues with the humanitarian dashboard, that also affect the grand bargain dashboard.

**Comment by andylolz** [comment]
Bumping this, six months on.

Various improvements have been added to this PR by @dalepotter, including:

 * More thorough tests (added in eaf8767)
 * A fix for the issue raised in https://github.com/IATI/IATI-Dashboard/issues/488#issuecomment-446545092, plus updated tests

As before, please let me or @dalepotter or @wendyrogers know if anything here requires further clarification.

**Comment by dalepotter** [comment]
Corresponding PR for changes to the narrative that appears on the IATI-Dashboard (in line with this PR): https://github.com/IATI/IATI-Dashboard/pull/530

Just to clarify my changes in 9df0798 mean that `humanitarian-scope/@type` and `humanitarian-scope/@code` must both be present and contain non-empty data to count in the 'Appeal or Emergency Details' column on the Dashboard. This change was made having spoken to @wendyrogers on this issue.

**Comment by wendyrogers** [comment]
Just to confirm that I am in agreement with changes made and would be great if these can be approved and merged before Christmas (if at all possible)

**Pull request merged**
